os: osx
osx_image: xcode9.3

before_install:
- brew remove --force --ignore-dependencies $(brew list)
- brew update
- brew upgrade
- brew install cmake llvm opam pkg-config
- opam init -y
- eval `opam config env`
- opam install -y llvm
- echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> ~/.bash_profile
- source ~/.bash_profile

install:
- make

script:
- ./test_parser.sh
- ./test_hello.sh

notifications:
  email: false
