os: osx
osx_image: xcode9.3

before_install:
- brew remove --force --ignore-dependencies $(brew list)
- brew update
- brew install cmake darcs git llvm mercurial opam pkg-config
- opam init -yq
- eval `opam config env`
- opam install -yq llvm
- echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> ~/.bash_profile
- source ~/.bash_profile

install:
- make

script:
- ./test_all.sh

notifications:
  email: false
