os: osx

before_install:
- brew unlink python # required, otherwise opam cannot be installed properly
- brew update
- brew upgrade
- brew install ocamlbuild
- brew install opam
- opam init -y
- eval `opam config env`
- opam update -y
- opam upgrade -y
- brew install llvm
- opam install -y llvm
- echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> ~/.bash_profile

install:
- make

script:
- ./test_parser.sh
- ./test_hello.sh

notifications:
  email: false
