os: osx

before_install:
- brew update
- brew install ocamlbuild
- brew install opam
- opam init
- eval `opam config env`
- brew install llvm
- opam install llvm

install:
- make

script:
- ./test_parser.sh

notifications:
  email: false
